
### Auction FetchAll
GET http://localhost:9000/auction
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZW1iZXIiOiJhZHNmQGFzZGYuY29tIiwiaWF0IjoxNjQyMTYxMzA1LCJleHAiOjE2NDIxNjQ5MDV9.UYF1FM1kQ_6BXfwLm97LPcOXwYMbb4eiKRn1EIvUFQ4

### Auction Create
POST http://localhost:9000/auction
Content-Type: application/json

{
  "auctionName": "オークション名",
  "colorId": 1,
  "subTitle": "サブタイトル",
  "startTime": "2022-01-11 12:21:12.000",
  "selectionImg": "画像"
}

### Auction FindOne
GET http://localhost:9000/auction/1

### Auction Update
PATCH http://localhost:9000/auction/1
Content-Type: application/json

{
  "auctionName": "オークション名（編集）"
}

### Auction Delete
DELETE http://localhost:9000/auction/1