
### Member FetchAll
GET http://localhost:9000/member

### Member Create
POST http://localhost:9000/member
Content-Type: application/json

{
  "name": "テスト　太郎",
  "companyName": "",
  "email": "asdf@asdf.com",
  "password": "asdfasdf"
}

### Member FindOne
GET http://localhost:9000/member/1

### Member Update
PATCH http://localhost:9000/member/1
Content-Type: application/json

{
  "name": "テスト　次郎"
}

### Member softDelete
DELETE http://localhost:9000/member/1