### Color FetchAll
GET http://localhost:9000/auction-color

### Color Create
POST http://localhost:9000/auction-color
Content-Type: application/json

{
  "name": "#ff0000"
}

### Color FindOne
GET http://localhost:9000/auction-color/2

### Color Update
PATCH http://localhost:9000/auction-color/2
Content-Type: application/json

{
  "name": "#2f2f2f"
}

### Color softDelete
DELETE http://localhost:9000/auction-color/3